/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    'grid',
    'flex',
    'border',
    'hover',
    'hover',
    'outline',
    {pattern: /flex-./},
    {pattern: /items-./},
    {pattern: /content-./},
    {pattern: /justify-./},
    {pattern: /outline-./, variants: ['hover']},
    {pattern: /cursor-./},
    {pattern: /m-./},
    {pattern: /mx-./},
    {pattern: /my-./},
    {pattern: /mt-./},
    {pattern: /mb-./},
    {pattern: /ml-./},
    {pattern: /mr-./},
    {pattern: /p-./},
    {pattern: /px-./},
    {pattern: /py-./},
    {pattern: /bg-./, variants: ['hover']},
    {pattern: /text-./, variants: ['focus', 'hover']},
    {pattern: /border-./, variants: ['hover']},
    {pattern: /grid-./},
    {pattern: /col-span-./},
    {pattern: /row-span-./},
    {pattern: /gap-./},
    {pattern: /space-./},
    {pattern: /animate-./},
    {pattern: /shadow-./, variants: ['hover']},
    {pattern: /w-./},
    {pattern: /h-./},
    {pattern: /rounded-./},
    {pattern: /m-./},
    {pattern: /-m-./},
  ]
}

